### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Septias** [dignifiedquire/dreamer#12]
- [ ] Login and import accounts
- [ ] Support all message-types
- [ ] Support Emojies
- [ ] Accept Contact Requests
- [ ] Create new Chats

**Comment by dignifiedquire** [comment]
Some other stuff we can pull in https://github.com/deltachat/dc40/issues/3

**Comment by Septias** [comment]
stall
